services:
  - type: web
    name: eleganzo-django
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_products && python manage.py reset_admin_from_env
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "eleganzo-mir.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: eleganzo-db
          property: connectionString

databases:
  - name: eleganzo-db
    plan: free
