 
services:
  - type: web
    name: eleganzo-django
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_products && python manage.py reset_admin_from_env
    startCommand: gunicorn config.wsgi:application